import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  function submitHandler(e) {
    e.preventDefault()

    const formData = {}

    Array.from(e.currentTarget.elements).map((field) => {
      if (!field.name) return

      formData[field.name] = field.value
    })

    fetch('/api/mail', {
      method: 'post',
      body: JSON.stringify(formData)
    })

    console.log(formData)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact Form</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Contact Form</h1>
        <style jsx>
          {`
            label {
              display: block;
            }
            button {
              color: white;
              display: block;
              padding: 1em 1.5em;
              background: blueviolet;
              border: 0;
              margin-top: 0.2rem;
              cursor: pointer;
            }
          `}
        </style>
        <form action='' onSubmit={(e) => submitHandler(e)}>
          <label htmlFor='name'>Name</label>
          <input type='text' id='name' name='text' />
          <label htmlFor='email'>Email</label>
          <input type='email' id='email' name='email' />

          <label htmlFor='message'>Message</label>
          <textarea id='message' name='message'></textarea>
          <button type='submit'>Submit</button>
        </form>
      </main>
    </div>
  )
}
